#!/usr/bin/env bash
# Displays the contents of the current directory in list format.
# Only displays the part of the name after the first dash.

list=(*)
for i in "${list[@]}"; do
  if [[ $i != .* ]]; then
    filename=$(basename "$i")
    echo "$filename" | cut -d '-' -f2
  fi
done
